config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get "products/message", to: "products#message"
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :additives, only: [:show]

  resources :products do
    member do
      put "like", to: "products#upvote"
      put "dislike", to: "products#downvote"
    end
  end

  get "queries", to: "queries#index"
  get 'howitworks', to: "pages#howwork"
  get 'method', to: "pages#method"
  get 'contact', to: "pages#contact"

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  # before_action :check_if_admin

  # def index
  #   @requests = Product.requests
  # end

  # private

  # def check_if_admin
  #   if not current_user.admin
  #     redirect_to root_path
  #   end
  # end
end

app/views/dashboard/_form.html.erb
<%= simple_form_for [request.product, request] do |f| %>
  <% if request.errors.any? %>
    <div class="errors-container">
      <ul>
        <% request.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.input :status, collection: ["pending", "accepted", "declined"] %>
  <%= f.submit "Update", class: "btn btn-blue" %>
<% end %>

app/views/dashboard/create_resquests.html.erb
<div class="container">
  <h2 class="text-center">My products creating requests</h2>
  <% @requests.each do |request| %>
    <div class="message">
      <div class="message-body">
        <p><strong> Product name:<%=  request.name %></strong></p>
        <% if request.photo != nil %>
          <p>Product photo: <%= cl_image_tag request.photo, height: 300, width: 400, crop: :fill %></p>
        <% end %>
        <p>Product sku:<%=  request.sku %></p>
      </div>
      <div class="message-status text-center">
        <div class="form-group">
          <%= render 'form', request: request %>
        </div>
      </div>
    </div>
  <% end %>
  <% @requests.each do |request| %>
    <% if policy(request).edit? %>
      <%= link_to "Update", edit_product_path(product) %>
    <% end %>
  <% end %>
</div>

app/views/dashboard/index.html.erb
<!-- <div class="container">
  <% @requests.each do |request| %>
    <h2><%= request.name %></h2>
    <p><%= request.status %></p>
  <% end %>
</div> -->