config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get "products/message", to: "products#message"
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :additives, only: [:show]

  resources :products do
    member do
      put "like", to: "products#upvote"
      put "dislike", to: "products#downvote"
    end
  end

  get "queries", to: "queries#index"
  get 'howitworks', to: "pages#howwork"
  get 'method', to: "pages#method"
  get 'contact', to: "pages#contact"

end

app/views/pages/contact.html.erb
<!-- contact us form -->
<div class="container" style="padding-bottom: 77px;">
  <div class="form-login2">
    <h2>Enviar un email</h2>
      <form action="/">
        <label for="fname">Nombre</label>
        <input type="text" id="fname" name="firstname" placeholder="Su nombre...">

        <label for="lname">Apellido</label>
        <input type="text" id="lname" name="lastname" placeholder="Su apellido...">

        <label for="country">País</label>
        <select id="country" name="country">
          <option value="australia">España</option>
          <option value="canada">Brasil</option>
          <option value="usa">Otro</option>
        </select>

        <label for="subject">Tema</label>
        <textarea id="subject" name="subject" placeholder="Escriba algo..." style="height:200px"></textarea>
        <div class="text-center">
          <input type="submit" value="Submit" class="btn submit-button">
        </div>
      </form>
  </div>
</div>
<%= render 'shared/footer' %>

app/views/pages/home.html.erb
<div class="home-wrapper">
    <div class="button-navbar gradient-fill" style="color: white;font-size: medium;text-decoration: none;">
      <%= link_to "Como funciona", howitworks_path, style: "color: white;font-size: medium;text-decoration: none;position: absolute;left: 18px;top: 10px;" %>
      <% if user_signed_in? %>
        <%= link_to "Sign out", destroy_user_session_path, :method => :delete, style: "color: white;font-size: text-transform: capitalize; medium;text-decoration: none;position: absolute;right: 18px;top: 10px;" %>
      <% else %>
        <%= link_to "Sign In", user_session_path, style: "color: white;font-size: medium;text-decoration: text-transform: capitalize;none;position: absolute;right: 18px;top: 10px;" %>
      <% end %>
    </div>
    <div class="banner">

      <div class="banner-content banner-container">
    	<%= image_tag("logo.png", height: 100, crop: :fill)%>
        <h1 style="text-transform: none !important;">eatamina</h1>
        <p style="" class="banner__tagline">¡Descifra lo que comes en un click!</p>

      </div>
    </div>
    <div class="gradient-fill" style="padding-bottom: 13vh;">
        <div class="row barcode-input" style="margin-left: 0px;margin-right: 0px; padding-bottom: 20px;">

    <div class="home__camera-button-wrap">
			<button class="home__camera-button" type="button" data-toggle="modal" data-target="#livestream_scanner">
				<i class="fa fa-camera" style="font-size:37px;color:#686868"></i>

			</button>
    	</div>
    </div>
    <p class="home__camera-prompt">ESCANEA EL CODIGO DE BARRAS</p>

    <div class="">
        		<div class="" style="padding-bottom: 20px;">
        			<%= form_tag root_path, method: :get do %>
                <%= text_field_tag :query,
                  params[:query],
                  class: "form-control form-css",
    							style: "width: 70%; text-align: center;",
                  id: "scanner_input",
                  placeholder: "Escribe el Codigo de Barras"
                %>
              <% end %>
        		</div><!-- /input-group -->
        	</div><!-- /.col-lg-6 -->

     </div><!-- /.row -->
        <div class="modal" id="livestream_scanner">
        	<div>
        		<div>
        				<div class="modal-body" style="position: absolute;top: 0;left: calc(50%);transform: translateX(-50%);">
        					<div id="interactive" class="viewport"></div>
        			</div>

        		</div><!-- /.modal-content -->
        	</div><!-- /.modal-dialog -->
        </div><!-- /.modal -->
</div>
 <% if user_signed_in? %>
<%= render 'shared/footer_main' %>
<% end %>

app/views/pages/howwork.html.erb
  <div class="detail-page">
        <div class="detail__photo-wrap">
           
              <%= image_tag 'https://cdn.britannica.com/700x450/57/43857-004-52EE48DE.jpg',  class:"detail__photo-method" %>
  
        </div>

<div class="container--regular" style="margin-top: 55px;">
            <div class="detail__product-info-section">
    <p class="detail__product-section-header">¿Como funciona?</p>
     <p class="detail__product-info-header" style="color: #1D1A1A;">
                   <strong>1 </strong>Escanea el código de barras del producto
     <p class="detail__product-body" style="text-align: justify; color: #686868;">
Para tener una mejor lectura, centre el código de barras delante de la cámara o puede escribirlo manualmente dentro de la celda.
                </p>
            </div>
            
</div>

<div class="container--regular" style="margin-top: 40px;">
            <div class="detail__product-info-section">
 
     <p class="detail__product-info-header" style="color: #1D1A1A;">
                   <strong>2 </strong>Recibe la información del producto
                </p>
     <p class="detail__product-body" style="text-align: justify; color: #686868;">
La calificación del producto se basa en 3 criterios:
              La calidad nutricional representa el 60% del puntaje. El método de cálculo se basa en las recomendaciones del Profesor Serge Hercberg.
              La presencia de aditivos en el producto representa el 30% del puntaje. De muchas fuentes que han estudiado la peligrosidad de los aditivos alimentarios, clasificamos los aditivos según su grado de nocividad: sin impacto (verde), dudoso (amarillo), evitar (anaranjado), nocivo (rojo).
              La dimensión biológica representa el 10% de la puntuación.
                </p>
            </div>
            
</div>
<div class="container--regular" style="margin-top: 40px;">
            <div class="detail__product-info-section">
 
     <p class="detail__product-info-header" style="color: #1D1A1A;">
                   <strong>3 </strong>Entiende los efectos sobre la salud de aditivo
                </p>
     <p class="detail__product-body" style="text-align: justify; color: #686868;">
Vaya a cada aditivo en su comida para comprender los problemas de comer con un solo clic.
                </p>
            </div>
             <%= image_tag 'http://nutritionglobal.com/wp-content/uploads/2015/01/Harmful-Effects-of-Food-Additives.jpg',  class:"detail__photo-method" %>
</div>

<%= render 'shared/footer' %>

app/views/pages/method.html.erb
  <div class="detail-page" style="padding-bottom: 89px;">
        <div class="detail__photo-wrap">
           
              <%= image_tag 'https://gastronomiaycia.republica.com/wp-content/uploads/2017/03/nutriscore-680x444.jpg',  class:"detail__photo-method" %>
  
        </div>

<div class="container--regular" style="margin-top: 55px;">
            <div class="detail__product-info-section">
    <p class="detail__product-section-header">Método de clasificación</p>
     <p class="detail__product-info-header" style="color: #1D1A1A;">
                   <strong>1 </strong>Calidad Nutricional
                </p>
     <p class="detail__product-body" style="text-align: justify; color: #686868;">
La calidad nutricional representa el <strong>60%</strong> del puntaje. El método de cálculo se basa en las recomendaciones del Profesor Serge Hercberg como parte de la Estrategia Nacional de Salud propuesta por el Estado y validada en la creación de Nutriscore. Este método tiene en cuenta los siguientes elementos: calorías, azúcar, sal, grasas saturadas, proteínas, fibras, frutas y verduras. 
                </p>
            </div>
            
</div>

<div class="container--regular" style="margin-top: 40px;">
            <div class="detail__product-info-section">
 
     <p class="detail__product-info-header" style="color: #1D1A1A;">
                   <strong>2 </strong>Dimensión Biológica
                </p>
     <p class="detail__product-body" style="text-align: justify; color: #686868;">
La dimensión biológica representa el <strong>10%</strong> de la puntuación. Los productos considerados orgánicos son aquellos con la etiqueta orgánica francesa (AB) y / o la etiqueta ecológica europea (Eurofeuille).
                </p>
            </div>
            
</div>
<div class="container--regular" style="margin-top: 40px;">
            <div class="detail__product-info-section">
 
     <p class="detail__product-info-header" style="color: #1D1A1A;">
                   <strong>3 </strong>Presencia de Aditivos
                </p>
     <p class="detail__product-body" style="text-align: justify; color: #686868;">
La presencia de aditivos en el producto representa el <strong>30%</strong> del puntaje. De muchas fuentes que han estudiado la peligrosidad de los aditivos alimentarios, clasificamos los aditivos según su grado de nocividad: sin impacto (verde), evitar (anaranjado), nocivo (rojo).
                </p>
            </div>
            
</div>

<%= render 'shared/footer' %>